# Generated by Django 5.0.6 on 2024-05-24 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0003_alter_user_usertype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='nation',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Nation',
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
