# Generated by Django 5.0.6 on 2024-05-24 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0005_companydetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='companydetails',
        ),
    ]
