# Generated by Django 5.0.6 on 2024-05-27 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0007_alter_user_options_alter_usertype_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelOptions(
            name='usertype',
            options={},
        ),
        migrations.AlterModelTable(
            name='user',
            table='usermaster',
        ),
        migrations.AlterModelTable(
            name='usertype',
            table='usertype',
        ),
    ]
