# Generated by Django 5.0.6 on 2024-05-29 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0008_alter_user_options_alter_usertype_options_and_more'),
        ('master', '0025_rename_usertype_companydetails_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CompanyID', to='master.companydetails'),
        ),
    ]
