# Generated by Django 5.0.6 on 2024-05-29 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0009_user_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='company',
        ),
    ]
