# Generated by Django 5.0.6 on 2024-06-10 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0011_user_otp'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='usermaster',
        ),
        migrations.AlterModelTable(
            name='usertype',
            table='usertype',
        ),
    ]
