# Generated by Django 5.0.6 on 2024-05-25 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0007_employeedepartment_employeedesignation_employeeimage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeedepartment',
            old_name='deprtment',
            new_name='department',
        ),
    ]
