# Generated by Django 5.0.6 on 2024-05-27 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0012_alter_employeeimage_employee_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeemaster',
            old_name='employee_id',
            new_name='employee_code',
        ),
    ]
