# Generated by Django 5.0.6 on 2024-05-27 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0014_alter_attendancemaster_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendancemaster',
            options={},
        ),
        migrations.AlterModelOptions(
            name='citymaster',
            options={},
        ),
        migrations.AlterModelOptions(
            name='companydetails',
            options={},
        ),
        migrations.AlterModelOptions(
            name='departmentmaster',
            options={},
        ),
        migrations.AlterModelOptions(
            name='designationmaster',
            options={},
        ),
        migrations.AlterModelOptions(
            name='employeedepartment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='employeedesignation',
            options={},
        ),
        migrations.AlterModelOptions(
            name='employeeimage',
            options={},
        ),
        migrations.AlterModelOptions(
            name='employeejoinmaster',
            options={},
        ),
        migrations.AlterModelOptions(
            name='employeemaster',
            options={},
        ),
        migrations.AlterModelOptions(
            name='nationmaster',
            options={},
        ),
        migrations.AlterModelOptions(
            name='statemaster',
            options={},
        ),
        migrations.AlterModelTable(
            name='attendancemaster',
            table='attendancemaster',
        ),
        migrations.AlterModelTable(
            name='citymaster',
            table='citymaster',
        ),
        migrations.AlterModelTable(
            name='companydetails',
            table='companydetails',
        ),
        migrations.AlterModelTable(
            name='departmentmaster',
            table='departmentmaster',
        ),
        migrations.AlterModelTable(
            name='designationmaster',
            table='designationmaster',
        ),
        migrations.AlterModelTable(
            name='employeedepartment',
            table='employeedepartment',
        ),
        migrations.AlterModelTable(
            name='employeedesignation',
            table='employeedesignation',
        ),
        migrations.AlterModelTable(
            name='employeeimage',
            table='employeeimage',
        ),
        migrations.AlterModelTable(
            name='employeejoinmaster',
            table='employeejoinmaster',
        ),
        migrations.AlterModelTable(
            name='employeemaster',
            table='employeemaster',
        ),
        migrations.AlterModelTable(
            name='nationmaster',
            table='nationmaster',
        ),
        migrations.AlterModelTable(
            name='statemaster',
            table='statemaster',
        ),
    ]
