# Generated by Django 5.0.6 on 2024-05-28 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0016_rolemaster'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='rolemaster',
            table=None,
        ),
    ]
