# Generated by Django 5.0.6 on 2024-05-28 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0017_alter_rolemaster_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='rolemaster',
        ),
    ]
