# Generated by Django 5.0.6 on 2024-05-28 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0018_delete_rolemaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='rolemaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'rolemaster',
            },
        ),
    ]
