# Generated by Django 5.0.6 on 2024-05-28 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0019_rolemaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeejoinmaster',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.rolemaster'),
        ),
    ]
