# Generated by Django 5.0.6 on 2024-05-28 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0020_employeejoinmaster_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeejoinmaster',
            name='join_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
