# Generated by Django 5.0.6 on 2024-05-29 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0008_alter_user_options_alter_usertype_options_and_more'),
        ('master', '0022_alter_employeeimage_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydetails',
            name='usertype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance_app.usertype'),
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='company_icon',
            field=models.ImageField(blank=True, null=True, upload_to='company_images'),
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_images'),
        ),
    ]
