# Generated by Django 5.0.6 on 2024-05-29 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0024_alter_companydetails_usertype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companydetails',
            old_name='usertype',
            new_name='user',
        ),
    ]
