# Generated by Django 5.0.6 on 2024-06-03 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0026_workingtime'),
    ]

    operations = [
        migrations.CreateModel(
            name='timebreakmaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tbreak', models.CharField(choices=[('LUNCH', 'Lunch Break'), ('TEA', 'Tea Break')], max_length=50)),
            ],
            options={
                'db_table': 'timebreakmaster',
            },
        ),
        migrations.AlterModelTable(
            name='workingtime',
            table='workingtime',
        ),
    ]
