# Generated by Django 5.0.6 on 2024-06-05 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0027_timebreakmaster_alter_workingtime_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timebreakmaster',
            name='tbreak',
            field=models.CharField(max_length=30),
        ),
        migrations.CreateModel(
            name='forgotcheckin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_time', models.DateTimeField(blank=True, null=True)),
                ('normal_login_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=15, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.companydetails')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.employeemaster')),
            ],
            options={
                'db_table': 'forgotcheckin',
            },
        ),
    ]
