# Generated by Django 5.0.6 on 2024-06-05 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0028_alter_timebreakmaster_tbreak_forgotcheckin'),
    ]

    operations = [
        migrations.AddField(
            model_name='forgotcheckin',
            name='location',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
