# Generated by Django 5.0.6 on 2024-06-10 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0031_employeemaster_company'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='attendancemaster',
            table='attendancemaster',
        ),
        migrations.AlterModelTable(
            name='citymaster',
            table='citymaster',
        ),
        migrations.AlterModelTable(
            name='companydetails',
            table='companydetails',
        ),
        migrations.AlterModelTable(
            name='departmentmaster',
            table='departmentmaster',
        ),
        migrations.AlterModelTable(
            name='designationmaster',
            table='designationmaster',
        ),
        migrations.AlterModelTable(
            name='employeedepartment',
            table='employeedepartment',
        ),
        migrations.AlterModelTable(
            name='employeedesignation',
            table='employeedesignation',
        ),
        migrations.AlterModelTable(
            name='employeeimage',
            table='employeeimage',
        ),
        migrations.AlterModelTable(
            name='employeejoinmaster',
            table='employeejoinmaster',
        ),
        migrations.AlterModelTable(
            name='employeemaster',
            table='employeemaster',
        ),
        migrations.AlterModelTable(
            name='forgotcheckin',
            table='forgotcheckin',
        ),
        migrations.AlterModelTable(
            name='nationmaster',
            table='nationmaster',
        ),
        migrations.AlterModelTable(
            name='rolemaster',
            table='rolemaster',
        ),
        migrations.AlterModelTable(
            name='statemaster',
            table='statemaster',
        ),
        migrations.AlterModelTable(
            name='timebreakmaster',
            table='timebreakmaster',
        ),
        migrations.AlterModelTable(
            name='workingtime',
            table='workingtime',
        ),
    ]
