# Generated by Django 5.0.6 on 2024-06-11 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0034_alter_leavemaster_table_leaveenquiry'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='leaveenquiry',
            table='leaveenquiry',
        ),
        migrations.CreateModel(
            name='approvedleave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Slno', models.IntegerField(blank=True, null=True)),
                ('from_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('approved_date', models.DateField(blank=True, null=True)),
                ('approved_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.employeemaster')),
                ('leave_enquiry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.leaveenquiry')),
            ],
        ),
    ]
