# Generated by Django 5.0.6 on 2024-06-11 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0035_alter_leaveenquiry_table_approvedleave'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='approvedleave',
            table='approvedleave',
        ),
    ]
