# Generated by Django 5.0.6 on 2024-06-11 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0036_alter_approvedleave_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveenquiry',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
