# Generated by Django 5.0.6 on 2024-06-11 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0037_leaveenquiry_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveenquiry',
            name='enquery_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
