# Generated by Django 5.0.6 on 2024-06-14 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0038_alter_leaveenquiry_enquery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveenquiry',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Approved'), (2, 'Rejected'), (3, 'Cancelled')], default=0),
        ),
    ]
