# Generated by Django 5.0.6 on 2024-06-22 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0040_addleave'),
    ]

    operations = [
        migrations.AddField(
            model_name='addleave',
            name='available_leave_balance',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
