# Generated by Django 5.0.6 on 2024-07-09 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0044_employeeprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancemaster',
            name='Slno',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
