# Generated by Django 5.0.6 on 2024-07-09 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0045_alter_attendancemaster_slno'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employeeprofile',
            table='employeeprofile',
        ),
    ]
