# Generated by Django 5.0.6 on 2024-07-10 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0047_bankdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='instagram',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='linkedin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='twitter',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
