# Generated by Django 5.0.6 on 2024-07-11 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0048_employeeprofile_instagram_employeeprofile_linkedin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='skill_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='skill_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='skill_3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='skill_4',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='skill_5',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
