# Generated by Django 5.0.6 on 2024-07-13 09:57

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0050_countdownstate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countdownstate',
            name='total_seconds',
        ),
        migrations.AddField(
            model_name='countdownstate',
            name='remaining_time',
            field=models.DurationField(blank=True, default=datetime.timedelta(seconds=32400), null=True),
        ),
        migrations.AddField(
            model_name='countdownstate',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='countdownstate',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='countdownstate',
            table='countdown',
        ),
    ]
