# Generated by Django 5.0.6 on 2024-07-18 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0052_remove_countdownstate_remaining_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeprofile',
            old_name='emergency_contact_person',
            new_name='guardian_email',
        ),
        migrations.RenameField(
            model_name='employeeprofile',
            old_name='emergency_phone',
            new_name='guardian_phone',
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='guardian_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='guardian_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
