# Generated by Django 5.0.6 on 2024-07-20 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0054_alter_employeeprofile_guardian_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countdownstate',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='countdownstate',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='countdownstate',
            name='start_time',
        ),
        migrations.AddField(
            model_name='countdownstate',
            name='total_seconds',
            field=models.FloatField(default=0),
        ),
        migrations.AlterModelTable(
            name='countdownstate',
            table='countdown_timer',
        ),
    ]
